import React, { createContext, useState, useEffect } from "react";

export const LanguageContext = createContext();

export const translations = {
  en: {
    brand_title: "DairyGuard AI",
    brand_sub: "SIH26111 — Feed & Silage Testing System",
    home: "🏠 Home",
    test_feed: "📷 Test Feed & Silage",
    find_vet: "👨‍⚕️ Field Officer Support",
    my_dash: "📊 My Dashboard",
    alerts: "🚨 Quality Alerts",
    history: "📜 History & Trends",
    choose_language: "🌐 Choose Language",
    login_btn: "🔑 Login / Register",
    logout: "🚪 Logout",
    hero_title: "Smart AI-Enabled Rapid Feed & Silage Quality Testing System",
    hero_desc: "Rapid non-laboratory AI visual screening for cattle feed and silage quality (GOOD, MODERATE, POOR). Detect spoilage, moisture imbalance, and mold spots instantly from a mobile photo.",
    test_now: "📷 Test Your Silage / Feed Now",
    view_history_btn: "📜 View Quality History & Trends →",
    take_photo: "📷 Take Photo / Upload Image",
    upload_gallery: "🖼️ Choose from Gallery",
    feed_type: "Feed Type",
    moisture_level: "Moisture Level",
    smell_rating: "Odor / Smell Rating",
    color_obs: "Visual Color",
    mold_visible: "Are visible mold/fungal spots present?",
    analyzing: "🔬 AI is analyzing feed quality...",
    result_title: "Silage & Feed Quality Result",
    good_quality: "🟢 GOOD QUALITY",
    moderate_quality: "🟡 MODERATE QUALITY",
    poor_quality: "🔴 POOR QUALITY",
    score_label: "Quality Score",
    recommendation_title: "AI Analysis & Recommendation",
    disclaimer: "Visual screening powered by AI. For critical ration decisions, laboratory testing may be conducted.",
    sf_alert_created: "🚨 Poor Quality Alert synced to Salesforce CRM & Regional Field Officer assigned.",
    yes: "Yes",
    no: "No",
    retake: "🔄 Retake / Choose New Image",
    save_and_next: "Save & Analyze",
    choose_lang_title: "🌐 Choose Language / भाषा चुनें / भाषा निवडा",
    english: "English (US/IN)",
    hindi: "हिंदी (Hindi)",
    marathi: "मराठी (Marathi)",
    registered_farmers: "Registered Farmers",
    samples_tested: "Feed Samples Tested",
    sf_crm_connected: "Salesforce CRM Connected",
    field_officers: "Field Officers Assigned",
    feature1_title: "Mobile Photo AI Screening",
    feature1_desc: "Take or upload a photo of your forage or silage. AI MobileNet visual analysis evaluates color, texture, and mold spots.",
    feature2_title: "Good / Moderate / Poor Score",
    feature2_desc: "Instantly classifies feed quality into GOOD (80-100%), MODERATE (50-79%), or POOR (<50%) with practical farmer recommendations.",
    feature3_title: "Salesforce CRM & Vet Alerts",
    feature3_desc: "Automated Salesforce CRM object sync (Farmer__c, Feed_Sample__c, Vet_Alert__c) dispatches regional field officers for poor quality feed.",
    login_prompt: "🔒 Login or Register to Test Silage & Feed Quality",
    login_desc: "Registered farmers can upload sample photos, receive AI quality scores, track feed history, and trigger Salesforce CRM poor-quality alerts.",
    login_to_acc: "Login to Account",
    reg_account: "Create Account & Register",
    full_name: "Full Name",
    email_addr: "Email Address",
    phone_num: "Mobile Number",
    password: "Password",
    confirm_pass: "Confirm Password",
    state: "State",
    district: "District",
    city: "City / Village",
    pincode: "Pincode",
    use_location: "📍 Use My Current Location",
    location_info: "Structured Location Info"
  },
  hi: {
    brand_title: "डेयरीगार्ड AI",
    brand_sub: "SIH26111 — हरा चारा एवं साइलेज गुणवत्ता जांच प्रणाली",
    home: "🏠 मुख्य पृष्ठ",
    test_feed: "📷 चारे की जांच करें",
    find_vet: "👨‍⚕️ क्षेत्र अधिकारी सहायता",
    my_dash: "📊 मेरा डैशबोर्ड",
    alerts: "🚨 गुणवत्ता अलर्ट",
    history: "📜 इतिहास एवं रुझान",
    choose_language: "🌐 भाषा चुनें (Choose Language)",
    login_btn: "🔑 लॉगिन / पंजीकरण",
    logout: "🚪 लॉग आउट",
    hero_title: "स्मार्ट AI-आधारित त्वरित चारा एवं साइलेज गुणवत्ता जांच प्रणाली",
    hero_desc: "AI इमेज विश्लेषण द्वारा पशु चारे और साइलेज की गुणवत्ता (GOOD, MODERATE, POOR) की त्वरित गैर-प्रयोगशाला जांच करें।",
    test_now: "📷 अभी अपने चारे/साइलेज की जांच करें →",
    view_history_btn: "📜 गुणवत्ता इतिहास और रुझान देखें →",
    take_photo: "📷 फोटो खींचें / अपलोड करें",
    upload_gallery: "🖼️ गैलरी से चुनें",
    feed_type: "चारे का प्रकार",
    moisture_level: "नमी का स्तर",
    smell_rating: "गंंध / गंध का आकलन",
    color_obs: "दृश्य रंग",
    mold_visible: "क्या फफूंद/उल्लू के धब्बे दिखाई दे रहे हैं?",
    analyzing: "🔬 AI चारे की गुणवत्ता का विश्लेषण कर रहा है...",
    result_title: "साइलेज एवं चारा गुणवत्ता परिणाम",
    good_quality: "🟢 उत्तम गुणवत्ता (GOOD)",
    moderate_quality: "🟡 मध्यम गुणवत्ता (MODERATE)",
    poor_quality: "🔴 खराब गुणवत्ता (POOR)",
    score_label: "गुणवत्ता स्कोर",
    recommendation_title: "AI विश्लेषण एवं सिफारिशें",
    disclaimer: "AI द्वारा दृश्य जांच। अति महत्वपूर्ण निर्णयों के लिए प्रयोगशाला परीक्षण किया जा सकता है।",
    sf_alert_created: "🚨 खराब चारे का अलर्ट सेल्सफोर्स CRM में भेजा गया एवं पशु अधिकारी नियुक्त किया गया।",
    yes: "हां",
    no: "नहीं",
    retake: "🔄 नई फोटो चुनें",
    save_and_next: "सुरक्षित करें एवं जांचें",
    choose_lang_title: "🌐 भाषा चुनें / Choose Language",
    english: "English (अंग्रेजी)",
    hindi: "हिंदी (Hindi)",
    marathi: "मराठी (Marathi)",
    registered_farmers: "पंजीकृत किसान",
    samples_tested: "जाँचे गए चारे के नमूने",
    sf_crm_connected: "सेल्सफोर्स CRM कनेक्टेड",
    field_officers: "नियुक्त क्षेत्र अधिकारी",
    feature1_title: "मोबाइल फोटो AI स्क्रीनिंग",
    feature1_desc: "चारे या साइलेज की फोटो लें। AI विजुअल विश्लेषण रंग, संरचना और फफूंद के धब्बों की जांच करता है।",
    feature2_title: "उत्तम / मध्यम / खराब स्कोर",
    feature2_desc: "चारे की गुणवत्ता को GOOD (80-100%), MODERATE (50-79%), या POOR (<50%) श्रेणी में विभाजित करता है।",
    feature3_title: "सेल्सफोर्स CRM एवं अलर्ट",
    feature3_desc: "खराब चारे की स्थिति में स्वचालित सेल्सफोर्स CRM ऑब्जेक्ट सिंक (Farmer__c, Feed_Sample__c, Vet_Alert__c)।",
    login_prompt: "🔒 चारे की गुणवत्ता जांचने के लिए लॉगिन या पंजीकरण करें",
    login_desc: "पंजीकृत किसान फोटो अपलोड कर सकते हैं, AI स्कोर प्राप्त कर सकते हैं और इतिहास ट्रैक कर सकते हैं।",
    login_to_acc: "अकाउंट में लॉगिन करें",
    reg_account: "अकाउंट बनाएं और पंजीकरण करें",
    full_name: "पूरा नाम",
    email_addr: "ईमेल पता",
    phone_num: "मोबाइल नंबर",
    password: "पासवर्ड",
    confirm_pass: "पासवर्ड की पुष्टि करें",
    state: "राज्य",
    district: "जिला",
    city: "शहर / गांव",
    pincode: "पिनकोड",
    use_location: "📍 मेरी वर्तमान लोकेशन का उपयोग करें",
    location_info: "स्थान की जानकारी"
  },
  mr: {
    brand_title: "डेअरीगार्ड AI",
    brand_sub: "SIH26111 — चारा आणि सायलेज गुणवत्ता तपासणी प्रणाली",
    home: "🏠 मुख्य पृष्ठ",
    test_feed: "📷 चारा तपासा",
    find_vet: "👨‍⚕️ क्षेत्र अधिकारी मदत",
    my_dash: "📊 माझे डॅशबोर्ड",
    alerts: "🚨 गुणवत्ता इशारे (Alerts)",
    history: "📜 इतिहास आणि कल",
    choose_language: "🌐 भाषा निवडा (Choose Language)",
    login_btn: "🔑 लॉगिन / नोंदणी",
    logout: "🚪 लॉग आउट",
    hero_title: "स्मार्ट AI-आधारित जलद चारा आणि सायलेज गुणवत्ता तपासणी प्रणाली",
    hero_desc: "AI इमेज विश्लेषणाद्वारे जनावरांचा चारा आणि सायलेजच्या गुणवत्तेची (GOOD, MODERATE, POOR) त्वरित तपासणी करा.",
    test_now: "📷 आता चारा/सायलेज तपासा →",
    view_history_btn: "📜 गुणवत्ता इतिहास आणि कल पहा →",
    take_photo: "📷 फोटो काढा / अपलोड करा",
    upload_gallery: "🖼️ गॅलरीमधून निवडा",
    feed_type: "चाऱ्याचा प्रकार",
    moisture_level: "ओलसरपणाचे प्रमाण (नमी)",
    smell_rating: "वास / गंध",
    color_obs: "दिसणारा रंग",
    mold_visible: "बुरशीचे किंवा काळे डाग दिसतात का?",
    analyzing: "🔬 AI गुणवत्तेचे विश्लेषण करत आहे...",
    result_title: "सायलेज आणि चारा गुणवत्ता निकाल",
    good_quality: "🟢 उत्तम गुणवत्ता (GOOD)",
    moderate_quality: "🟡 मध्यम गुणवत्ता (MODERATE)",
    poor_quality: "🔴 खराब गुणवत्ता (POOR)",
    score_label: "गुणवत्ता गुण (Score)",
    recommendation_title: "AI विश्लेषण आणि शिफारसी",
    disclaimer: "AI द्वारे दृश्य तपासणी. महत्त्वाच्या निर्णयासाठी प्रयोगशाळा चाचणी केली जाऊ शकते.",
    sf_alert_created: "🚨 खराब चाऱ्याचा इशारा सेल्सफोर्स CRM वर पाठवला आणि क्षेत्र अधिकारी नियुक्त केला.",
    yes: "होय",
    no: "नाही",
    retake: "🔄 नवीन फोटो निवडा",
    save_and_next: "जतन करा आणि तपासा",
    choose_lang_title: "🌐 भाषा निवडा / Choose Language",
    english: "English (इंग्रजी)",
    hindi: "हिंदी (Hindi)",
    marathi: "मराठी (Marathi)",
    registered_farmers: "नोंदणीकृत शेतकरी",
    samples_tested: "तपासलेले चाऱ्याचे नमुने",
    sf_crm_connected: "सेल्सफोर्स CRM जोडलेले",
    field_officers: "नियुक्त क्षेत्र अधिकारी",
    feature1_title: "मोबाईल फोटो AI स्क्रीनिंग",
    feature1_desc: "चाऱ्याचा किंवा सायलेजचा फोटो काढा. AI विश्लेषण रंग, रचना आणि बुरशीच्या डागांची तपासणी करते.",
    feature2_title: "उत्तम / मध्यम / खराब गुण",
    feature2_desc: "चाऱ्याच्या गुणवत्तेचे उत्तम (80-100%), मध्यम (50-79%) किंवा खराब (<50%) श्रेणीत वर्गीकरण करते.",
    feature3_title: "सेल्सफोर्स CRM आणि इशारे",
    feature3_desc: "खराब चाऱ्याच्या स्थितीत स्वयंचलित सेल्सफोर्स CRM ऑब्जेक्ट सिंक (Farmer__c, Feed_Sample__c, Vet_Alert__c).",
    login_prompt: "🔒 सायलेज आणि चाऱ्याची गुणवत्ता तपासण्यासाठी लॉगिन किंवा नोंदणी करा",
    login_desc: "नोंदणीकृत शेतकरी फोटो अपलोड करू शकतात, AI गुण मिळवू शकतात आणि इतिहास पाहू शकतात.",
    login_to_acc: "खात्यामध्ये लॉगिन करा",
    reg_account: "खाते तयार करा आणि नोंदणी करा",
    full_name: "पूर्ण नाव",
    email_addr: "ईमेल पत्ता",
    phone_num: "मोबाईल नंबर",
    password: "पासवर्ड",
    confirm_pass: "पासवर्डची पुष्टी करा",
    state: "राज्य",
    district: "जिल्हा",
    city: "शहर / गाव",
    pincode: "पिनकोड",
    use_location: "📍 माझे सध्याचे स्थान वापरा",
    location_info: "स्थानाची माहिती"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("app_lang") || "en");

  const changeLanguage = (langCode) => {
    setLang(langCode);
    localStorage.setItem("app_lang", langCode);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
